version: "3.8"

networks:
  kafka_network:
    driver: bridge

volumes:
  kafka_data:
  zookeeper_data:

services:

  microservicio-productor:
    container_name: microservicio-productor
    image: ingfaraya/desarrollo-cloud-native-1-sumativa3-productor:latest
    ports:
      - "8080:8080"
    networks:
      - kafka_network
    restart: on-failure

  microservicio-consumidor:
    container_name: microservicio-consumidor
    image: ingfaraya/desarrollo-cloud-native-1-sumativa3-consumidor:latest
    ports:
      - "8081:8081"
    networks:
      - kafka_network
    restart: on-failure

  microservicio-alertas:
    container_name: microservicio-alertas
    image: ingfaraya/desarrollo-cloud-native-1-sumativa3-alertas:latest
    ports:
      - "8082:8082"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@legx51juninivtkl_medium?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=admin
      - spring.datasource.password=Febrero$2025
    networks:
      - kafka_network
    restart: on-failure

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kafka_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    volumes:
      - zookeeper_data:/var/lib/zookeeper

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kafka_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181
    volumes:
      - zookeeper_data:/var/lib/zookeeper

  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kafka_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 42181:2181
    volumes:
      - zookeeper_data:/var/lib/zookeeper

  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    networks:
      - kafka_network
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka-1
    networks:
      - kafka_network
    ports:
      - 8090:8087
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
